spring:
  application: demo

  datasource:
    username: postgres
    password: 2205
    url: jdbc:postgresql://localhost:5433/postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl: validate


server:
  host: localhost
  port: 8080
  sslEnabled: true